### PR TITLE
Cryptographically-ensured leaderboard

### PR DESCRIPTION
**Pull request by nicholasngai**
This is perhaps a bit of an overkill PR, but I figured it’s about time we really did something permanent about the leaderboard issue. Essentially, it uses symmetric-key cryptography in order to verify key aspects of the process leading up to the posting of the WPM on the leaderboard.

Because this uses cryptography, this adds OpenSSL as a dependency and the Python Cryptography library as as a requirement. It uses the Fernet format for encryption, which is built upon AES-128 and a SHA-256 HMAC as primitives. Fernet provides timestamped and authenticated “tokens” which will be used as the actual tokens. The full spec is available [https://github.com/fernet/spec/blob/master/Spec.md](here).

Three tokens are implemented:
- `p_token`: A token verifying that the paragraph claimed by the client was actually sent by the server
- `s_token`: A token verifying the true start time (when the first `/analyze` request is made) and tying that time to a particular paragraph
- `wpm_token`: A token verifying that the client’s claimed WPM was actually validly computed by the server

Each token in the chain will only be issued if the verification for the previous token succeeds, ensuring the full CATS test is completed upon the issuing of `wpm_token`.

The following details the generation and verification steps associated with each token. Note that `E(` and `D(` refer to encryption and decryption with the Fernet format, respectively, and `H(` refers to a SHA-256 digest.
- `p_token` = `E(H(paragraph))`
    - Generated upon receiving a request to `/request_paragraph`
    - Sent to client along with the paragraph text
- `s_token` = `E(H(paragraph))`
    - Generated upon receipt of an `/analyze` request containing a valid `p_token`
    - The `p_token` is considered valid if and only if the following conditions are met:
        - `p_token` is not stale (timestamp is newer than 1 hour)
        - `p_token` has not already been successfully used
        - `D(p_token)` matches `H(prompted_text)`
    - While it has the same contents as a `p_token`, the `s_token` is generated because its timestamp matches the actual start time for typing on the client, which ties the start time to a particular paragraph.
    - Sent to client along with the analysis results (WPM and accuracy)
- `wpm_token` = `E(wpm)`
    - Generated upon receipt of an `/analyze` request containing a valid `s_token` and whose `prompted_text` = `typed_text`, signifying the completion of the test with 100% accuracy
    - The `s_token` is considered valid if and only if the following conditions are met:
        - `s_token` is not stale (timestamp is newer than 1 hour)
        - `s_token` has not already been successfully used
        - `D(s_token)` matches `H(prompted_text)`
        - Timestamp of `s_token` is close to `start_time` received from client (within 60 seconds)
        - Server’s time is close to `end_time` received from client (within 60 seconds)
    - Additionally, the server will only generate `wpm_token` if the calculated `wpm` is less than `200` to act as a sanity check. Otherwise, the `/analyze` response will contain no `wpm_token`.
    - This is what will be sent to the `/record_wpm` endpoint, which only posts to the leaderboard upon receipt of a valid `wpm_token`. The `wpm_token` is considered valid if and only if the following conditions are met:
        - `wpm_token` is not stale (timestamp is newer than 1 hour)
        - `wpm_token` has not already been successfully used
        - `D(wpm_token)` matches `wpm` received from client

Note that because all used tokens are stored for their period of freshness, they also essentially act as nonces, preventing trivial replay attacks on the `/analyze` or `/record_wpm` endpoints. The encryption keys are relatively short-term, always stored in memory and regenerating whenever the program is restarted, so there shouldn’t be much of a problem in terms of post-compromise security.

Because the action of typing is ultimately performed entirely on the client computer, there is no foolproof way of guaranteeing that false results do not make it onto the leaderboard. However, this pull request aims simply to raise the barrier enough to deter the casual CS 61A student from making false posts to the leaderboard in a mostly cryptographically ensured way while remaining completely transparent to the end-user.

_P.S.: I am in no way an expert in any of this and also am in no way an expert in Python, so by all means, do critique/edit my code in case something doesn’t work. Thanks!_

### CODE REVIEW

**Comment by rahularya50** [comment]
I'll need to test this later - possibly in a few days, due to the power outage.

Quick question though - does this work with the local client as well, or will it require changes to `gui.py` to support the local server as well?

Also, thanks for your contributions! You're probably spending more time on the server than I did, tbh! 🐱

**Comment by nicholasngai** [comment]
`gui.py` is theoretically unchanged (although upon closer inspection, it kind of looks like my array-to-JSON changes for the `/analyze` endpoint somehow made it in here… maybe it’ll go away when #1 is merged).

The only files changed are `App.js` to support the storing and sending of the tokens (which can really be anything) and `flask_app.py`. I basically wrapped `gui.analyze` and `gui.request_paragraph` so that instead of just passing through the requests, `flask_app.py` directly calls those associated methods and then appends to the output before it is sent in the response.

**Comment by nicholasngai** [comment]
Also, hmmm, I just realized that I need to send a `p_token` when the multiplier version is called, as well. Let me push some changes first.

**Comment by nicholasngai** [comment]
I was looking into the erroneous behavior for the local GUI. I’m not entirely sure where the issue would be, and I wasn’t able to reproduce it on my local device.

The code code for the Flask app is set up so that all the endpoints still work without tokens (but they just won’t return new tokens) except for `record_wpm`. Could you expand on the error you’re getting?

**Comment by nicholasngai** [comment]
Spoke too soon. I updated `App.js` to expect JSON data from `/request_paragraph`, but `flask_app.py` originally took `gui.py`'s plaintext response and wrapped it in JSON, so the client worked with `flask_app.py` but not `gui.py`. I updated `gui.py` to send JSON as well , and `flask_app.py` will just append to that before sending it as a response so that the client works with a local GUI.

**Comment by nicholasngai** [comment]
Hmmm, I’ve been thinking about it a bit (this seems slightly like a necro). I’m slightly tempted to turn all those tokens into JWT tokens. I’m going to try something in a bit.

**Pull request closed without merging**
