### PR TITLE
JWT to reduce leaderboard spam

### PR DESCRIPTION
**Pull request by nicholasngai**
*I’m just going to copy most of this from PR #2 since I just branched off of that branch. I basically took all the tokens and turned them into JWT so that there is some standardization to it. They also use HMAC and aren’t encrypted anymore, but that shouldn’t be an issue. Please see that PR for further info on verification of tokens and conditions for issuing following tokens. The notation has changed, but the principles are the same.*

This PR essentially adds tokens to each step of the typing test process so that students aren’t just able to spam the `POST /record_wpm` endpoint and get themselves on the leaderboard. These tokens are implemented in JWT under the HS256 scheme, and their claims are as follows:

Three tokens are implemented:
- `p_token`: A token verifying that the paragraph claimed by the client was actually sent by the server
  - `hash`: A SHA-256 hash of the paragraph to verify the paragraph was actually sent by the 
server
  - `exp`: The expiration of the token
- `s_token`: A token verifying the true start time (when the first `/analyze` request is made) and tying that time to a particular paragraph
  - `hash` A SHA-256 hash of the paragraph to tie the paragraph to the start time
  - `iat`: The time the token was issued (the time the user started typing the paragraph)
  - `exp`: The expiration of the token
- `wpm_token`: A token verifying that the client’s claimed WPM was actually validly computed by the server
  - `wpm`: The user’s claimed computed WPM, verified by the server
  - `exp`: The expiration of the token

Note that because all used tokens are stored for their period of freshness, they also essentially act as nonces, preventing trivial replay attacks on the /analyze or /record_wpm endpoints. The encryption keys are relatively short-term, always stored in memory and regenerating whenever the program is restarted, so there shouldn’t be much of a problem in terms of post-compromise security.

Because the action of typing is ultimately performed entirely on the client computer, there is no foolproof way of guaranteeing that false results do not make it onto the leaderboard. However, this pull request aims simply to raise the barrier enough to deter the casual CS 61A student from making false posts to the leaderboard in a mostly cryptographically ensured way while remaining completely transparent to the end-user.

*P.S.: I am in no way an expert in any of this and also am in no way an expert in Python, so by all means, do critique/edit my code in case something doesn’t work. Thanks!*

### CODE REVIEW

**Comment by rahularya50** [comment]
Awesome! Let's talk about this on Wednesday in the software meeting (yes, you're accepted). 

One important thing to do before merging is to update the local client as well. On Wednesday, we can sort out how you can have access to `gui.py` so the relevant changes can be made there as well. I imagine it'd just be passing the tokens through to the local client, but I haven't looked at this latest set of changes thoroughly yet.

Thanks again for your contributions!

**Comment by nicholasngai** [comment]
Yep, I definitely meant to make this a draft PR, but I… missed the button and accidentally made it a fully fledged PR. Whoops.

**Comment by nicholasngai** [comment]
> Awesome! Let's talk about this on Wednesday in the software meeting (yes, you're accepted).

When’s the software meeting, by the way?

**Comment by rahularya50** [comment]
Uh, 1-3pm on Wednesdays in Soda 373, and 4-6pm on Mondays in the same room. If you can't make either of these times, we can figure something else out.

**Comment by rahularya50** [comment]
Oh no I realized I didn't actually put the meeting times on the interest form. whoops. Hopefully that won't be an issue.

**Comment by nicholasngai** [comment]
I changed my mind about the crypto. I’m just going to scrap the branch and uses sessions instead like a normal person.

**Pull request closed without merging**
